# Generated by Django 6.0.8 on 2026-09-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código PIN')),
                ('status', models.CharField(choices=[('LOBBY', 'Esperando jugadores'), ('RUNNING', 'En curso'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='LOBBY', max_length=20, verbose_name='Estado')),
                ('current_question', models.PositiveIntegerField(default=0, verbose_name='Índice de pregunta actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada en')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada en')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_quiz_games', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrión')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='quizzes.quiz', verbose_name='Cuestionario')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntuación')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Respuestas correctas')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Racha actual')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz_games.game', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game_participations', to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Jugador de Partida',
                'verbose_name_plural': 'Jugadores de Partida',
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='¿Fue correcta?')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Puntos otorgados')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_games.gameplayer', verbose_name='Jugador')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_answers', to='quizzes.question', verbose_name='Pregunta')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_selections', to='quizzes.answer', verbose_name='Respuesta seleccionada')),
            ],
            options={
                'verbose_name': 'Respuesta de Jugador',
                'verbose_name_plural': 'Respuestas de Jugadores',
            },
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_player_per_quiz_game'),
        ),
        migrations.AddConstraint(
            model_name='playeranswer',
            constraint=models.UniqueConstraint(fields=('game_player', 'question'), name='unique_answer_per_player_question'),
        ),
    ]
