# Generated by Django 6.0.8 on 2026-09-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_games', '0001_initial'),
        ('quizzes', '0002_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada en'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_question',
            field=models.PositiveIntegerField(default=0, verbose_name='Pregunta actual'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha de aciertos'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Unido en'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Respondido en'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='is_correct',
            field=models.BooleanField(verbose_name='¿Respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_selections', to='quizzes.answer', verbose_name='Respuesta elegida'),
        ),
    ]
