# Generated by Django 6.0.8 on 2026-09-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_games', '0002_alter_game_created_at_alter_game_current_question_and_more'),
        ('quizzes', '0003_alter_answer_text_alter_question_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_question',
            field=models.PositiveIntegerField(default=0, verbose_name='Índice pregunta actual'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha actual'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='is_correct',
            field=models.BooleanField(verbose_name='¿Fue correcta?'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_selections', to='quizzes.answer', verbose_name='Respuesta seleccionada'),
        ),
    ]
