# Generated by Django 6.0.8 on 2026-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_games', '0003_alter_game_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio oficial de pregunta'),
        ),
    ]
