# Generated by Django 6.0.8 on 2026-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_games', '0004_game_question_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='¿Liquidado a Profile?'),
        ),
    ]
