# Generated by Django 6.0.8 on 2026-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_games', '0005_gameplayer_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='avatar_body',
            field=models.CharField(default='body_yellow', max_length=50, verbose_name='Cuerpo del Avatar'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='avatar_clothes',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ropa del Avatar'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='avatar_face',
            field=models.CharField(default='face_calm', max_length=50, verbose_name='Expresión del Avatar'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='avatar_head',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sombrero del Avatar'),
        ),
    ]
