# Generated by Django 6.0.8 on 2026-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Texto de respuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1000, verbose_name='Puntos base'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='Tiempo límite (s)'),
        ),
    ]
